name: CPU check
on:
  workflow_dispatch:
jobs:
  check:
    runs-on: macos-latest
    steps:
      - name: mac info
        run: |
          sysctl -n machdep.cpu.brand_string
          echo "cores: $(sysctl -n hw.ncpu)"
          echo "mem: $(sysctl -n hw.memsize)"
          system_profiler SPDisplaysDataType
          sw_vers
